### Задания на повторение материала

**Задание 1**

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно.

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


**Задание 2**

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = a.reshape(2, 6)
print(a1)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [4]:
a2 = a.reshape(6, 2)
print(a2)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [5]:
a3 = a.reshape(3, 4)
print(a3)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [6]:
a4 = a.reshape(4, 3)
print(a4)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [7]:
a5 = a.reshape(12, 1)
print(a5)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


**Задание 3**

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [8]:
a1 = a.reshape(2, -1)
print(a1)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [9]:
a2 = a.reshape(6, -1)
print(a2)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [10]:
a3 = a.reshape(-1, 4)
print(a3)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [11]:
a4 = a.reshape(-1, 3)
print(a4)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [12]:
a5 = a.reshape(12, -1)
print(a5)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


**Задание 4**

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [13]:
print('Размерность массива a:', a.ndim)

Размерность массива a: 1


In [14]:
print('Размерность массива а5:', a5.ndim)

Размерность массива а5: 2


**Задание 5**

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [15]:
x = np.random.randn(3, 4)
print(x)

[[ 0.12181797 -1.29482609  1.31858369  0.00611004]
 [-1.25915777  2.77797665 -1.65925702 -0.69347532]
 [ 0.30021184 -0.07488516  0.2538127   0.16659517]]


In [16]:
print(x.size)

12


In [17]:
x1 = x.flatten()
print(x1)

[ 0.12181797 -1.29482609  1.31858369  0.00611004 -1.25915777  2.77797665
 -1.65925702 -0.69347532  0.30021184 -0.07488516  0.2538127   0.16659517]


In [18]:
print(x1.size)

12


**Задание 6**

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [19]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


**Задание 7**

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [20]:
b = np.arange(20, 1, -2).reshape(1, 10)
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


In [21]:
print(a.ndim)

1


In [22]:
print(b.ndim)

2


**Задание 8**

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [23]:
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [24]:
b = np.ones((3, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [25]:
v = np.vstack((a, b))
print(v)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
print(v.size)

10


**Задание 9**

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [27]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [28]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [30]:
B = A.dot(At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [31]:
print(B.shape)

(4, 4)


In [32]:
b = np.linalg.inv(B)
print(b)

LinAlgError: Singular matrix

**Задание 10**

Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [33]:
np.random.seed(42)

**Задание 11**

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [34]:
c = np.random.randint(0, 16, size=16)
print(c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


**Задание 12**

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [35]:
C = c.reshape(4, 4)
print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [36]:
D = B + C * 10
print(D)

[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [37]:
print(np.linalg.det(D))

-28511999.999999944


In [38]:
print(np.linalg.matrix_rank(D))

4


In [39]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


**Задание 13**

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [40]:
D_inv = np.where(D_inv < 0, 0, 1)
print(D_inv)

[[1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]]


In [41]:
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [42]:
print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [43]:
E = np.where(D_inv == 1, B, C)
print(E)

[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
